//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlDiffFramework.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".")]
        public string LeftSqlDirectory {
            get {
                return ((string)(this["LeftSqlDirectory"]));
            }
            set {
                this["LeftSqlDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".")]
        public string RightSqlDirectory {
            get {
                return ((string)(this["RightSqlDirectory"]));
            }
            set {
                this["RightSqlDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NewVersion {
            get {
                return ((bool)(this["NewVersion"]));
            }
            set {
                this["NewVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TandemButton_Checked {
            get {
                return ((bool)(this["TandemButton_Checked"]));
            }
            set {
                this["TandemButton_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TurboSortButton_Checked {
            get {
                return ((bool)(this["TurboSortButton_Checked"]));
            }
            set {
                this["TurboSortButton_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseLocalDataButton_Checked {
            get {
                return ((bool)(this["UseLocalDataButton_Checked"]));
            }
            set {
                this["UseLocalDataButton_Checked"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("catalog.xml")]
        public string UpdateCatalogFile {
            get {
                return ((string)(this["UpdateCatalogFile"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime UpdateChecked {
            get {
                return ((global::System.DateTime)(this["UpdateChecked"]));
            }
            set {
                this["UpdateChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int UnreachableRepository {
            get {
                return ((int)(this["UnreachableRepository"]));
            }
            set {
                this["UnreachableRepository"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["WindowState"]));
            }
            set {
                this["WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LeftCsvDirectory {
            get {
                return ((string)(this["LeftCsvDirectory"]));
            }
            set {
                this["LeftCsvDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RightCsvDirectory {
            get {
                return ((string)(this["RightCsvDirectory"]));
            }
            set {
                this["RightCsvDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoHighlightButton_Checked {
            get {
                return ((bool)(this["AutoHighlightButton_Checked"]));
            }
            set {
                this["AutoHighlightButton_Checked"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UpdateRepository {
            get {
                return ((string)(this["UpdateRepository"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--")]
        public string LeftConnectionName {
            get {
                return ((string)(this["LeftConnectionName"]));
            }
            set {
                this["LeftConnectionName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--")]
        public string RightConnectionName {
            get {
                return ((string)(this["RightConnectionName"]));
            }
            set {
                this["RightConnectionName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoExecuteButton_Checked {
            get {
                return ((bool)(this["AutoExecuteButton_Checked"]));
            }
            set {
                this["AutoExecuteButton_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public decimal MaxColumnWidth {
            get {
                return ((decimal)(this["MaxColumnWidth"]));
            }
            set {
                this["MaxColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowElapsedTimes {
            get {
                return ((bool)(this["ShowElapsedTimes"]));
            }
            set {
                this["ShowElapsedTimes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public decimal CommandTimeout {
            get {
                return ((decimal)(this["CommandTimeout"]));
            }
            set {
                this["CommandTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoDiffButton_Checked {
            get {
                return ((bool)(this["AutoDiffButton_Checked"]));
            }
            set {
                this["AutoDiffButton_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle WindowPosition {
            get {
                return ((global::System.Drawing.Rectangle)(this["WindowPosition"]));
            }
            set {
                this["WindowPosition"] = value;
            }
        }
        
        /// <summary>
        /// Number of days between update checks
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Number of days between update checks")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal UpdateCheckInterval {
            get {
                return ((decimal)(this["UpdateCheckInterval"]));
            }
            set {
                this["UpdateCheckInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public decimal MaxHighlightedRowsPerChunk {
            get {
                return ((decimal)(this["MaxHighlightedRowsPerChunk"]));
            }
            set {
                this["MaxHighlightedRowsPerChunk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50000")]
        public decimal MaxHighlightedRowsTotal {
            get {
                return ((decimal)(this["MaxHighlightedRowsTotal"]));
            }
            set {
                this["MaxHighlightedRowsTotal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfConnectionDetails xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <ConnectionDetails>
    <ConnectionName>local-master</ConnectionName>
    <ConnectionString>Data Source=.\SQLEXPRESS;Initial Catalog=master;Integrated Security=True;Persist Security Info=True</ConnectionString>
    <DbType>SqlServer</DbType>
    <RememberPassword>false</RememberPassword>
    <Description>local SSExpress, master DB</Description>
  </ConnectionDetails>
  <ConnectionDetails>
    <ConnectionName>local-AdvWorks</ConnectionName>
    <ConnectionString>Data Source=.\SQLEXPRESS;Initial Catalog=AdventureWorks;Integrated Security=True;Persist Security Info=True</ConnectionString>
    <DbType>SqlServer</DbType>
    <RememberPassword>false</RememberPassword>
    <Description>local SSExpress, AdventureWorks DB</Description>
  </ConnectionDetails>
</ArrayOfConnectionDetails>")]
        public global::CleanCode.DatabaseControls.Support.ConnectionDetailsCollection ConnectionList {
            get {
                return ((global::CleanCode.DatabaseControls.Support.ConnectionDetailsCollection)(this["ConnectionList"]));
            }
            set {
                this["ConnectionList"] = value;
            }
        }
    }
}
